name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'

    - name: Clear Go cache (if any)
      run: |
        rm -rf $GOPATH/pkg/mod
        rm -rf $HOME/.cache/go-build
        echo "Go cache cleared"

    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

    - name: Build binary
      run: go build -o main .

    - name: Upload binary as release asset
      uses: actions/upload-artifact@v3
      with:
        name: main
        path: ./main

    - name: Trigger Deployment Repository
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.REPO_DEPLOY_TOKEN }}
        repository: coffee-chris94/go-app-container
        event-type: build_container
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

